INSERT INTO `[PREFIX_TABLE]city_translations` (`city_id`, `locale`, `name`, `prefix`) VALUES
(1, 'vi', 'Hà Nội', 'Thành Phố'),
(2, 'vi', 'Hà Giang', 'Tỉnh'),
(3, 'vi', 'Cao Bằng', 'Tỉnh'),
(4, 'vi', 'Bắc Kạn', 'Tỉnh'),
(5, 'vi', 'Tuyên Quang', 'Tỉnh'),
(6, 'vi', 'Lào Cai', 'Tỉnh'),
(7, 'vi', 'Điện Biên', 'Tỉnh'),
(8, 'vi', 'Lai Châu', 'Tỉnh'),
(9, 'vi', 'Sơn La', 'Tỉnh'),
(10, 'vi', 'Yên Bái', 'Tỉnh'),
(11, 'vi', 'Hòa Bình', 'Tỉnh'),
(12, 'vi', 'Thái Nguyên', 'Tỉnh'),
(13, 'vi', 'Lạng Sơn', 'Tỉnh'),
(14, 'vi', 'Quảng Ninh', 'Tỉnh'),
(15, 'vi', 'Bắc Giang', 'Tỉnh'),
(16, 'vi', 'Phú Thọ', 'Tỉnh'),
(17, 'vi', 'Vĩnh Phúc', 'Tỉnh'),
(18, 'vi', 'Bắc Ninh', 'Tỉnh'),
(19, 'vi', 'Hải Dương', 'Tỉnh'),
(20, 'vi', 'Hải Phòng', 'Thành Phố'),
(21, 'vi', 'Hưng Yên', 'Tỉnh'),
(22, 'vi', 'Thái Bình', 'Tỉnh'),
(23, 'vi', 'Hà Nam', 'Tỉnh'),
(24, 'vi', 'Nam Định', 'Tỉnh'),
(25, 'vi', 'Ninh Bình', 'Tỉnh'),
(26, 'vi', 'Thanh Hóa', 'Tỉnh'),
(27, 'vi', 'Nghệ An', 'Tỉnh'),
(28, 'vi', 'Hà Tĩnh', 'Tỉnh'),
(29, 'vi', 'Quảng Bình', 'Tỉnh'),
(30, 'vi', 'Quảng Trị', 'Tỉnh'),
(31, 'vi', 'Thừa Thiên Huế', 'Tỉnh'),
(32, 'vi', 'Đà Nẵng', 'Thành Phố'),
(33, 'vi', 'Quảng Nam', 'Tỉnh'),
(34, 'vi', 'Quảng Ngãi', 'Tỉnh'),
(35, 'vi', 'Bình Định', 'Tỉnh'),
(36, 'vi', 'Phú Yên', 'Tỉnh'),
(37, 'vi', 'Khánh Hòa', 'Tỉnh'),
(38, 'vi', 'Ninh Thuận', 'Tỉnh'),
(39, 'vi', 'Bình Thuận', 'Tỉnh'),
(40, 'vi', 'Kon Tum', 'Tỉnh'),
(41, 'vi', 'Gia Lai', 'Tỉnh'),
(42, 'vi', 'Đắk Lắk', 'Tỉnh'),
(43, 'vi', 'Đắk Nông', 'Tỉnh'),
(44, 'vi', 'Lâm Đồng', 'Tỉnh'),
(45, 'vi', 'Bình Phước', 'Tỉnh'),
(46, 'vi', 'Tây Ninh', 'Tỉnh'),
(47, 'vi', 'Bình Dương', 'Tỉnh'),
(48, 'vi', 'Đồng Nai', 'Tỉnh'),
(49, 'vi', 'Bà Rịa - Vũng Tàu', 'Tỉnh'),
(50, 'vi', 'Hồ Chí Minh', 'Thành Phố'),
(51, 'vi', 'Long An', 'Tỉnh'),
(52, 'vi', 'Tiền Giang', 'Tỉnh'),
(53, 'vi', 'Bến Tre', 'Tỉnh'),
(54, 'vi', 'Trà Vinh', 'Tỉnh'),
(55, 'vi', 'Vĩnh Long', 'Tỉnh'),
(56, 'vi', 'Đồng Tháp', 'Tỉnh'),
(57, 'vi', 'An Giang', 'Tỉnh'),
(58, 'vi', 'Kiên Giang', 'Tỉnh'),
(59, 'vi', 'Cần Thơ', 'Thành Phố'),
(60, 'vi', 'Hậu Giang', 'Tỉnh'),
(61, 'vi', 'Sóc Trăng', 'Tỉnh'),
(62, 'vi', 'Bạc Liêu', 'Tỉnh'),
(63, 'vi', 'Cà Mau', 'Tỉnh');
COMMIT;
