INSERT INTO `[PREFIX_TABLE]district_translations` (`district_id`, `locale`, `name`, `prefix`) VALUES
(1, 'vi', 'Ba Đình', 'Quận'),
(2, 'vi', 'Hoàn Kiếm', 'Quận'),
(3, 'vi', 'Tây Hồ', 'Quận'),
(4, 'vi', 'Long Biên', 'Quận'),
(5, 'vi', 'Cầu Giấy', 'Quận'),
(6, 'vi', 'Đống Đa', 'Quận'),
(7, 'vi', 'Hai Bà Trưng', 'Quận'),
(8, 'vi', 'Hoàng Mai', 'Quận'),
(9, 'vi', 'Thanh Xuân', 'Quận'),
(10, 'vi', 'Sóc Sơn', 'Huyện'),
(11, 'vi', 'Đông Anh', 'Huyện'),
(12, 'vi', 'Gia Lâm', 'Huyện'),
(13, 'vi', 'Từ Liêm', 'Huyện'),
(14, 'vi', 'Thanh Trì', 'Huyện'),
(15, 'vi', 'Mê Linh', 'Huyện'),
(16, 'vi', 'Hà Đông', 'Quận'),
(17, 'vi', 'Sơn Tây', 'Thị Xã'),
(18, 'vi', 'Ba Vì', 'Huyện'),
(19, 'vi', 'Phúc Thọ', 'Huyện'),
(20, 'vi', 'Đan Phượng', 'Huyện'),
(21, 'vi', 'Hoài Đức', 'Huyện'),
(22, 'vi', 'Quốc Oai', 'Huyện'),
(23, 'vi', 'Thạch Thất', 'Huyện'),
(24, 'vi', 'Chương Mỹ', 'Huyện'),
(25, 'vi', 'Thanh Oai', 'Huyện'),
(26, 'vi', 'Thường Tín', 'Huyện'),
(27, 'vi', 'Phú Xuyên', 'Huyện'),
(28, 'vi', 'Ứng Hòa', 'Huyện'),
(29, 'vi', 'Mỹ Đức', 'Huyện'),
(30, 'vi', 'Hà Giang', 'Thị Xã'),
(31, 'vi', 'Đồng Văn', 'Huyện'),
(32, 'vi', 'Mèo Vạc', 'Huyện'),
(33, 'vi', 'Yên Minh', 'Huyện'),
(34, 'vi', 'Quản Bạ', 'Huyện'),
(35, 'vi', 'Vị Xuyên', 'Huyện'),
(36, 'vi', 'Bắc Mê', 'Huyện'),
(37, 'vi', 'Hoàng Su Phì', 'Huyện'),
(38, 'vi', 'Xín Mần', 'Huyện'),
(39, 'vi', 'Bắc Quang', 'Huyện'),
(40, 'vi', 'Quang Bình', 'Huyện'),
(41, 'vi', 'Cao Bằng', 'Thị Xã'),
(42, 'vi', 'Bảo Lâm', 'Huyện'),
(43, 'vi', 'Bảo Lạc', 'Huyện'),
(44, 'vi', 'Thông Nông', 'Huyện'),
(45, 'vi', 'Hà Quảng', 'Huyện'),
(46, 'vi', 'Trà Lĩnh', 'Huyện'),
(47, 'vi', 'Trùng Khánh', 'Huyện'),
(48, 'vi', 'Hạ Lang', 'Huyện'),
(49, 'vi', 'Quảng Uyên', 'Huyện'),
(50, 'vi', 'Phục Hoà', 'Huyện'),
(51, 'vi', 'Hoà An', 'Huyện'),
(52, 'vi', 'Nguyên Bình', 'Huyện'),
(53, 'vi', 'Thạch An', 'Huyện'),
(54, 'vi', 'Bắc Kạn', 'Thị Xã'),
(55, 'vi', 'Pác Nặm', 'Huyện'),
(56, 'vi', 'Ba Bể', 'Huyện'),
(57, 'vi', 'Ngân Sơn', 'Huyện'),
(58, 'vi', 'Bạch Thông', 'Huyện'),
(59, 'vi', 'Chợ Đồn', 'Huyện'),
(60, 'vi', 'Chợ Mới', 'Huyện'),
(61, 'vi', 'Na Rì', 'Huyện'),
(62, 'vi', 'Tuyên Quang', 'Thị Xã'),
(63, 'vi', 'Nà Hang', 'Huyện'),
(64, 'vi', 'Chiêm Hóa', 'Huyện'),
(65, 'vi', 'Hàm Yên', 'Huyện'),
(66, 'vi', 'Yên Sơn', 'Huyện'),
(67, 'vi', 'Sơn Dương', 'Huyện'),
(68, 'vi', 'Lào Cai', 'Thành Phố'),
(69, 'vi', 'Bát Xát', 'Huyện'),
(70, 'vi', 'Mường Khương', 'Huyện'),
(71, 'vi', 'Si Ma Cai', 'Huyện'),
(72, 'vi', 'Bắc Hà', 'Huyện'),
(73, 'vi', 'Bảo Thắng', 'Huyện'),
(74, 'vi', 'Bảo Yên', 'Huyện'),
(75, 'vi', 'Sa Pa', 'Huyện'),
(76, 'vi', 'Văn Bàn', 'Huyện'),
(77, 'vi', 'Điện Biên Phủ', 'Thành Phố'),
(78, 'vi', 'Mường Lay', 'Thị Xã'),
(79, 'vi', 'Mường Nhé', 'Huyện'),
(80, 'vi', 'Mường Chà', 'Huyện'),
(81, 'vi', 'Tủa Chùa', 'Huyện'),
(82, 'vi', 'Tuần Giáo', 'Huyện'),
(83, 'vi', 'Điện Biên', 'Huyện'),
(84, 'vi', 'Điện Biên Đông', 'Huyện'),
(85, 'vi', 'Mường Ảng', 'Huyện'),
(86, 'vi', 'Lai Châu', 'Thị Xã'),
(87, 'vi', 'Tam Đường', 'Huyện'),
(88, 'vi', 'Mường Tè', 'Huyện'),
(89, 'vi', 'Sìn Hồ', 'Huyện'),
(90, 'vi', 'Phong Thổ', 'Huyện'),
(91, 'vi', 'Than Uyên', 'Huyện'),
(92, 'vi', 'Tân Uyên', 'Huyện'),
(93, 'vi', 'Sơn La', 'Thành Phố'),
(94, 'vi', 'Quỳnh Nhai', 'Huyện'),
(95, 'vi', 'Thuận Châu', 'Huyện'),
(96, 'vi', 'Mường La', 'Huyện'),
(97, 'vi', 'Bắc Yên', 'Huyện'),
(98, 'vi', 'Phù Yên', 'Huyện'),
(99, 'vi', 'Mộc Châu', 'Huyện'),
(100, 'vi', 'Yên Châu', 'Huyện'),
(101, 'vi', 'Mai Sơn', 'Huyện'),
(102, 'vi', 'Sông Mã', 'Huyện'),
(103, 'vi', 'Sốp Cộp', 'Huyện'),
(104, 'vi', 'Yên Bái', 'Thành Phố'),
(105, 'vi', 'Nghĩa Lộ', 'Thị Xã'),
(106, 'vi', 'Lục Yên', 'Huyện'),
(107, 'vi', 'Văn Yên', 'Huyện'),
(108, 'vi', 'Mù Cang Chải', 'Huyện'),
(109, 'vi', 'Trấn Yên', 'Huyện'),
(110, 'vi', 'Trạm Tấu', 'Huyện'),
(111, 'vi', 'Văn Chấn', 'Huyện'),
(112, 'vi', 'Yên Bình', 'Huyện'),
(113, 'vi', 'Hòa Bình', 'Thành Phố'),
(114, 'vi', 'Đà Bắc', 'Huyện'),
(115, 'vi', 'Kỳ Sơn', 'Huyện'),
(116, 'vi', 'Lương Sơn', 'Huyện'),
(117, 'vi', 'Kim Bôi', 'Huyện'),
(118, 'vi', 'Cao Phong', 'Huyện'),
(119, 'vi', 'Tân Lạc', 'Huyện'),
(120, 'vi', 'Mai Châu', 'Huyện'),
(121, 'vi', 'Lạc Sơn', 'Huyện'),
(122, 'vi', 'Yên Thủy', 'Huyện'),
(123, 'vi', 'Lạc Thủy', 'Huyện'),
(124, 'vi', 'Thái Nguyên', 'Thành Phố'),
(125, 'vi', 'Sông Công', 'Thị Xã'),
(126, 'vi', 'Định Hóa', 'Huyện'),
(127, 'vi', 'Phú Lương', 'Huyện'),
(128, 'vi', 'Đồng Hỷ', 'Huyện'),
(129, 'vi', 'Võ Nhai', 'Huyện'),
(130, 'vi', 'Đại Từ', 'Huyện'),
(131, 'vi', 'Phổ Yên', 'Huyện'),
(132, 'vi', 'Phú Bình', 'Huyện'),
(133, 'vi', 'Lạng Sơn', 'Thành Phố'),
(134, 'vi', 'Tràng Định', 'Huyện'),
(135, 'vi', 'Bình Gia', 'Huyện'),
(136, 'vi', 'Văn Lãng', 'Huyện'),
(137, 'vi', 'Cao Lộc', 'Huyện'),
(138, 'vi', 'Văn Quan', 'Huyện'),
(139, 'vi', 'Bắc Sơn', 'Huyện'),
(140, 'vi', 'Hữu Lũng', 'Huyện'),
(141, 'vi', 'Chi Lăng', 'Huyện'),
(142, 'vi', 'Lộc Bình', 'Huyện'),
(143, 'vi', 'Đình Lập', 'Huyện'),
(144, 'vi', 'Hạ Long', 'Thành Phố'),
(145, 'vi', 'Móng Cái', 'Thành Phố'),
(146, 'vi', 'Cẩm Phả', 'Thị Xã'),
(147, 'vi', 'Uông Bí', 'Thị Xã'),
(148, 'vi', 'Bình Liêu', 'Huyện'),
(149, 'vi', 'Tiên Yên', 'Huyện'),
(150, 'vi', 'Đầm Hà', 'Huyện'),
(151, 'vi', 'Hải Hà', 'Huyện'),
(152, 'vi', 'Ba Chẽ', 'Huyện'),
(153, 'vi', 'Vân Đồn', 'Huyện'),
(154, 'vi', 'Hoành Bồ', 'Huyện'),
(155, 'vi', 'Đông Triều', 'Huyện'),
(156, 'vi', 'Yên Hưng', 'Huyện'),
(157, 'vi', 'Cô Tô', 'Huyện'),
(158, 'vi', 'Bắc Giang', 'Thành Phố'),
(159, 'vi', 'Yên Thế', 'Huyện'),
(160, 'vi', 'Tân Yên', 'Huyện'),
(161, 'vi', 'Lạng Giang', 'Huyện'),
(162, 'vi', 'Lục Nam', 'Huyện'),
(163, 'vi', 'Lục Ngạn', 'Huyện'),
(164, 'vi', 'Sơn Động', 'Huyện'),
(165, 'vi', 'Yên Dũng', 'Huyện'),
(166, 'vi', 'Việt Yên', 'Huyện'),
(167, 'vi', 'Hiệp Hòa', 'Huyện'),
(168, 'vi', 'Việt Trì', 'Thành Phố'),
(169, 'vi', 'Phú Thọ', 'Thị Xã'),
(170, 'vi', 'Đoan Hùng', 'Huyện'),
(171, 'vi', 'Hạ Hoà', 'Huyện'),
(172, 'vi', 'Thanh Ba', 'Huyện'),
(173, 'vi', 'Phù Ninh', 'Huyện'),
(174, 'vi', 'Yên Lập', 'Huyện'),
(175, 'vi', 'Cẩm Khê', 'Huyện'),
(176, 'vi', 'Tam Nông', 'Huyện'),
(177, 'vi', 'Lâm Thao', 'Huyện'),
(178, 'vi', 'Thanh Sơn', 'Huyện'),
(179, 'vi', 'Thanh Thuỷ', 'Huyện'),
(180, 'vi', 'Tân Sơn', 'Huyện'),
(181, 'vi', 'Vĩnh Yên', 'Thành Phố'),
(182, 'vi', 'Phúc Yên', 'Thị Xã'),
(183, 'vi', 'Lập Thạch', 'Huyện'),
(184, 'vi', 'Tam Dương', 'Huyện'),
(185, 'vi', 'Tam Đảo', 'Huyện'),
(186, 'vi', 'Bình Xuyên', 'Huyện'),
(187, 'vi', 'Yên Lạc', 'Huyện'),
(188, 'vi', 'Vĩnh Tường', 'Huyện'),
(189, 'vi', 'Sông Lô', 'Huyện'),
(190, 'vi', 'Bắc Ninh', 'Thành Phố'),
(191, 'vi', 'Yên Phong', 'Huyện'),
(192, 'vi', 'Quế Võ', 'Huyện'),
(193, 'vi', 'Tiên Du', 'Huyện'),
(194, 'vi', 'Từ Sơn', 'Thị Xã'),
(195, 'vi', 'Thuận Thành', 'Huyện'),
(196, 'vi', 'Gia Bình', 'Huyện'),
(197, 'vi', 'Lương Tài', 'Huyện'),
(198, 'vi', 'Hải Dương', 'Thành Phố'),
(199, 'vi', 'Chí Linh', 'Huyện'),
(200, 'vi', 'Nam Sách', 'Huyện'),
(201, 'vi', 'Kinh Môn', 'Huyện'),
(202, 'vi', 'Kim Thành', 'Huyện'),
(203, 'vi', 'Thanh Hà', 'Huyện'),
(204, 'vi', 'Cẩm Giàng', 'Huyện'),
(205, 'vi', 'Bình Giang', 'Huyện'),
(206, 'vi', 'Gia Lộc', 'Huyện'),
(207, 'vi', 'Tứ Kỳ', 'Huyện'),
(208, 'vi', 'Ninh Giang', 'Huyện'),
(209, 'vi', 'Thanh Miện', 'Huyện'),
(210, 'vi', 'Hồng Bàng', 'Quận'),
(211, 'vi', 'Ngô Quyền', 'Quận'),
(212, 'vi', 'Lê Chân', 'Quận'),
(213, 'vi', 'Hải An', 'Quận'),
(214, 'vi', 'Kiến An', 'Quận'),
(215, 'vi', 'Đồ Sơn', 'Quận'),
(216, 'vi', 'Kinh Dương', 'Quận'),
(217, 'vi', 'Thuỷ Nguyên', 'Huyện'),
(218, 'vi', 'An Dương', 'Huyện'),
(219, 'vi', 'An Lão', 'Huyện'),
(220, 'vi', 'Kiến Thụy', 'Huyện'),
(221, 'vi', 'Tiên Lãng', 'Huyện'),
(222, 'vi', 'Vĩnh Bảo', 'Huyện'),
(223, 'vi', 'Cát Hải', 'Huyện'),
(224, 'vi', 'Bạch Long Vĩ', 'Huyện'),
(225, 'vi', 'Hưng Yên', 'Thành Phố'),
(226, 'vi', 'Văn Lâm', 'Huyện'),
(227, 'vi', 'Văn Giang', 'Huyện'),
(228, 'vi', 'Yên Mỹ', 'Huyện'),
(229, 'vi', 'Mỹ Hào', 'Huyện'),
(230, 'vi', 'Ân Thi', 'Huyện'),
(231, 'vi', 'Khoái Châu', 'Huyện'),
(232, 'vi', 'Kim Động', 'Huyện'),
(233, 'vi', 'Tiên Lữ', 'Huyện'),
(234, 'vi', 'Phù Cừ', 'Huyện'),
(235, 'vi', 'Thái Bình', 'Thành Phố'),
(236, 'vi', 'Quỳnh Phụ', 'Huyện'),
(237, 'vi', 'Hưng Hà', 'Huyện'),
(238, 'vi', 'Đông Hưng', 'Huyện'),
(239, 'vi', 'Thái Thụy', 'Huyện'),
(240, 'vi', 'Tiền Hải', 'Huyện'),
(241, 'vi', 'Kiến Xương', 'Huyện'),
(242, 'vi', 'Vũ Thư', 'Huyện'),
(243, 'vi', 'Phủ Lý', 'Thành Phố'),
(244, 'vi', 'Duy Tiên', 'Huyện'),
(245, 'vi', 'Kim Bảng', 'Huyện'),
(246, 'vi', 'Thanh Liêm', 'Huyện'),
(247, 'vi', 'Bình Lục', 'Huyện'),
(248, 'vi', 'Lý Nhân', 'Huyện'),
(249, 'vi', 'Nam Định', 'Thành Phố'),
(250, 'vi', 'Mỹ Lộc', 'Huyện'),
(251, 'vi', 'Vụ Bản', 'Huyện'),
(252, 'vi', 'Ý Yên', 'Huyện'),
(253, 'vi', 'Nghĩa Hưng', 'Huyện'),
(254, 'vi', 'Nam Trực', 'Huyện'),
(255, 'vi', 'Trực Ninh', 'Huyện'),
(256, 'vi', 'Xuân Trường', 'Huyện'),
(257, 'vi', 'Giao Thủy', 'Huyện'),
(258, 'vi', 'Hải Hậu', 'Huyện'),
(259, 'vi', 'Ninh Bình', 'Thành Phố'),
(260, 'vi', 'Tam Điệp', 'Thị Xã'),
(261, 'vi', 'Nho Quan', 'Huyện'),
(262, 'vi', 'Gia Viễn', 'Huyện'),
(263, 'vi', 'Hoa Lư', 'Huyện'),
(264, 'vi', 'Yên Khánh', 'Huyện'),
(265, 'vi', 'Kim Sơn', 'Huyện'),
(266, 'vi', 'Yên Mô', 'Huyện'),
(267, 'vi', 'Thanh Hóa', 'Thành Phố'),
(268, 'vi', 'Bỉm Sơn', 'Thị Xã'),
(269, 'vi', 'Sầm Sơn', 'Thị Xã'),
(270, 'vi', 'Mường Lát', 'Huyện'),
(271, 'vi', 'Quan Hóa', 'Huyện'),
(272, 'vi', 'Bá Thước', 'Huyện'),
(273, 'vi', 'Quan Sơn', 'Huyện'),
(274, 'vi', 'Lang Chánh', 'Huyện'),
(275, 'vi', 'Ngọc Lặc', 'Huyện'),
(276, 'vi', 'Cẩm Thủy', 'Huyện'),
(277, 'vi', 'Thạch Thành', 'Huyện'),
(278, 'vi', 'Hà Trung', 'Huyện'),
(279, 'vi', 'Vĩnh Lộc', 'Huyện'),
(280, 'vi', 'Yên Định', 'Huyện'),
(281, 'vi', 'Thọ Xuân', 'Huyện'),
(282, 'vi', 'Thường Xuân', 'Huyện'),
(283, 'vi', 'Triệu Sơn', 'Huyện'),
(284, 'vi', 'Thiệu Hoá', 'Huyện'),
(285, 'vi', 'Hoằng Hóa', 'Huyện'),
(286, 'vi', 'Hậu Lộc', 'Huyện'),
(287, 'vi', 'Nga Sơn', 'Huyện'),
(288, 'vi', 'Như Xuân', 'Huyện'),
(289, 'vi', 'Như Thanh', 'Huyện'),
(290, 'vi', 'Nông Cống', 'Huyện'),
(291, 'vi', 'Đông Sơn', 'Huyện'),
(292, 'vi', 'Quảng Xương', 'Huyện'),
(293, 'vi', 'Tĩnh Gia', 'Huyện'),
(294, 'vi', 'Vinh', 'Thành Phố'),
(295, 'vi', 'Cửa Lò', 'Thị Xã'),
(296, 'vi', 'Thái Hoà', 'Thị Xã'),
(297, 'vi', 'Quế Phong', 'Huyện'),
(298, 'vi', 'Quỳ Châu', 'Huyện'),
(299, 'vi', 'Kỳ Sơn', 'Huyện'),
(300, 'vi', 'Tương Dương', 'Huyện'),
(301, 'vi', 'Nghĩa Đàn', 'Huyện'),
(302, 'vi', 'Quỳ Hợp', 'Huyện'),
(303, 'vi', 'Quỳnh Lưu', 'Huyện'),
(304, 'vi', 'Con Cuông', 'Huyện'),
(305, 'vi', 'Tân Kỳ', 'Huyện'),
(306, 'vi', 'Anh Sơn', 'Huyện'),
(307, 'vi', 'Diễn Châu', 'Huyện'),
(308, 'vi', 'Yên Thành', 'Huyện'),
(309, 'vi', 'Đô Lương', 'Huyện'),
(310, 'vi', 'Thanh Chương', 'Huyện'),
(311, 'vi', 'Nghi Lộc', 'Huyện'),
(312, 'vi', 'Nam Đàn', 'Huyện'),
(313, 'vi', 'Hưng Nguyên', 'Huyện'),
(314, 'vi', 'Hà Tĩnh', 'Thành Phố'),
(315, 'vi', 'Hồng Lĩnh', 'Thị Xã'),
(316, 'vi', 'Hương Sơn', 'Huyện'),
(317, 'vi', 'Đức Thọ', 'Huyện'),
(318, 'vi', 'Vũ Quang', 'Huyện'),
(319, 'vi', 'Nghi Xuân', 'Huyện'),
(320, 'vi', 'Can Lộc', 'Huyện'),
(321, 'vi', 'Hương Khê', 'Huyện'),
(322, 'vi', 'Thạch Hà', 'Huyện'),
(323, 'vi', 'Cẩm Xuyên', 'Huyện'),
(324, 'vi', 'Kỳ Anh', 'Huyện'),
(325, 'vi', 'Lộc Hà', 'Huyện'),
(326, 'vi', 'Đồng Hới', 'Thành Phố'),
(327, 'vi', 'Minh Hóa', 'Huyện'),
(328, 'vi', 'Tuyên Hóa', 'Huyện'),
(329, 'vi', 'Quảng Trạch', 'Huyện'),
(330, 'vi', 'Bố Trạch', 'Huyện'),
(331, 'vi', 'Quảng Ninh', 'Huyện'),
(332, 'vi', 'Lệ Thủy', 'Huyện'),
(333, 'vi', 'Đông Hà', 'Thành Phố'),
(334, 'vi', 'Quảng Trị', 'Thị Xã'),
(335, 'vi', 'Vĩnh Linh', 'Huyện'),
(336, 'vi', 'Hướng Hóa', 'Huyện'),
(337, 'vi', 'Gio Linh', 'Huyện'),
(338, 'vi', 'Đa Krông', 'Huyện'),
(339, 'vi', 'Cam Lộ', 'Huyện'),
(340, 'vi', 'Triệu Phong', 'Huyện'),
(341, 'vi', 'Hải Lăng', 'Huyện'),
(342, 'vi', 'Cồn Cỏ', 'Huyện'),
(343, 'vi', 'Huế', 'Thành Phố'),
(344, 'vi', 'Phong Điền', 'Huyện'),
(345, 'vi', 'Quảng Điền', 'Huyện'),
(346, 'vi', 'Phú Vang', 'Huyện'),
(347, 'vi', 'Hương Thủy', 'Huyện'),
(348, 'vi', 'Hương Trà', 'Huyện'),
(349, 'vi', 'A Lưới', 'Huyện'),
(350, 'vi', 'Phú Lộc', 'Huyện'),
(351, 'vi', 'Nam Đông', 'Huyện'),
(352, 'vi', 'Liên Chiểu', 'Quận'),
(353, 'vi', 'Thanh Khê', 'Quận'),
(354, 'vi', 'Hải Châu', 'Quận'),
(355, 'vi', 'Sơn Trà', 'Quận'),
(356, 'vi', 'Ngũ Hành Sơn', 'Quận'),
(357, 'vi', 'Cẩm Lệ', 'Quận'),
(358, 'vi', 'Hoà Vang', 'Huyện'),
(359, 'vi', 'Hoàng Sa', 'Huyện'),
(360, 'vi', 'Tam Kỳ', 'Thành Phố'),
(361, 'vi', 'Hội An', 'Thành Phố'),
(362, 'vi', 'Tây Giang', 'Huyện'),
(363, 'vi', 'Đông Giang', 'Huyện'),
(364, 'vi', 'Đại Lộc', 'Huyện'),
(365, 'vi', 'Điện Bàn', 'Huyện'),
(366, 'vi', 'Duy Xuyên', 'Huyện'),
(367, 'vi', 'Quế Sơn', 'Huyện'),
(368, 'vi', 'Nam Giang', 'Huyện'),
(369, 'vi', 'Phước Sơn', 'Huyện'),
(370, 'vi', 'Hiệp Đức', 'Huyện'),
(371, 'vi', 'Thăng Bình', 'Huyện'),
(372, 'vi', 'Tiên Phước', 'Huyện'),
(373, 'vi', 'Bắc Trà My', 'Huyện'),
(374, 'vi', 'Nam Trà My', 'Huyện'),
(375, 'vi', 'Núi Thành', 'Huyện'),
(376, 'vi', 'Phú Ninh', 'Huyện'),
(377, 'vi', 'Nông Sơn', 'Huyện'),
(378, 'vi', 'Quảng Ngãi', 'Thành Phố'),
(379, 'vi', 'Bình Sơn', 'Huyện'),
(380, 'vi', 'Trà Bồng', 'Huyện'),
(381, 'vi', 'Tây Trà', 'Huyện'),
(382, 'vi', 'Sơn Tịnh', 'Huyện'),
(383, 'vi', 'Tư Nghĩa', 'Huyện'),
(384, 'vi', 'Sơn Hà', 'Huyện'),
(385, 'vi', 'Sơn Tây', 'Huyện'),
(386, 'vi', 'Minh Long', 'Huyện'),
(387, 'vi', 'Nghĩa Hành', 'Huyện'),
(388, 'vi', 'Mộ Đức', 'Huyện'),
(389, 'vi', 'Đức Phổ', 'Huyện'),
(390, 'vi', 'Ba Tơ', 'Huyện'),
(391, 'vi', 'Lý Sơn', 'Huyện'),
(392, 'vi', 'Qui Nhơn', 'Thành Phố'),
(393, 'vi', 'An Lão', 'Huyện'),
(394, 'vi', 'Hoài Nhơn', 'Huyện'),
(395, 'vi', 'Hoài Ân', 'Huyện'),
(396, 'vi', 'Phù Mỹ', 'Huyện'),
(397, 'vi', 'Vĩnh Thạnh', 'Huyện'),
(398, 'vi', 'Tây Sơn', 'Huyện'),
(399, 'vi', 'Phù Cát', 'Huyện'),
(400, 'vi', 'An Nhơn', 'Huyện'),
(401, 'vi', 'Tuy Phước', 'Huyện'),
(402, 'vi', 'Vân Canh', 'Huyện'),
(403, 'vi', 'Tuy Hòa', 'Thành Phố'),
(404, 'vi', 'Sông Cầu', 'Thị Xã'),
(405, 'vi', 'Đồng Xuân', 'Huyện'),
(406, 'vi', 'Tuy An', 'Huyện'),
(407, 'vi', 'Sơn Hòa', 'Huyện'),
(408, 'vi', 'Sông Hinh', 'Huyện'),
(409, 'vi', 'Tây Hoà', 'Huyện'),
(410, 'vi', 'Phú Hoà', 'Huyện'),
(411, 'vi', 'Đông Hoà', 'Huyện'),
(412, 'vi', 'Nha Trang', 'Thành Phố'),
(413, 'vi', 'Cam Ranh', 'Thị Xã'),
(414, 'vi', 'Cam Lâm', 'Huyện'),
(415, 'vi', 'Vạn Ninh', 'Huyện'),
(416, 'vi', 'Ninh Hòa', 'Huyện'),
(417, 'vi', 'Khánh Vĩnh', 'Huyện'),
(418, 'vi', 'Diên Khánh', 'Huyện'),
(419, 'vi', 'Khánh Sơn', 'Huyện'),
(420, 'vi', 'Trường Sa', 'Huyện'),
(421, 'vi', 'Phan Rang-Tháp Chàm', 'Thành Phố'),
(422, 'vi', 'Bác Ái', 'Huyện'),
(423, 'vi', 'Ninh Sơn', 'Huyện'),
(424, 'vi', 'Ninh Hải', 'Huyện'),
(425, 'vi', 'Ninh Phước', 'Huyện'),
(426, 'vi', 'Thuận Bắc', 'Huyện'),
(427, 'vi', 'Thuận Nam', 'Huyện'),
(428, 'vi', 'Phan Thiết', 'Thành Phố'),
(429, 'vi', 'La Gi', 'Thị Xã'),
(430, 'vi', 'Tuy Phong', 'Huyện'),
(431, 'vi', 'Bắc Bình', 'Huyện'),
(432, 'vi', 'Hàm Thuận Bắc', 'Huyện'),
(433, 'vi', 'Hàm Thuận Nam', 'Huyện'),
(434, 'vi', 'Tánh Linh', 'Huyện'),
(435, 'vi', 'Đức Linh', 'Huyện'),
(436, 'vi', 'Hàm Tân', 'Huyện'),
(437, 'vi', 'Phú Quí', 'Huyện'),
(438, 'vi', 'Kon Tum', 'Thành Phố'),
(439, 'vi', 'Đắk Glei', 'Huyện'),
(440, 'vi', 'Ngọc Hồi', 'Huyện'),
(441, 'vi', 'Đắk Tô', 'Huyện'),
(442, 'vi', 'Kon Plông', 'Huyện'),
(443, 'vi', 'Kon Rẫy', 'Huyện'),
(444, 'vi', 'Đắk Hà', 'Huyện'),
(445, 'vi', 'Sa Thầy', 'Huyện'),
(446, 'vi', 'Tu Mơ Rông', 'Huyện'),
(447, 'vi', 'Pleiku', 'Thành Phố'),
(448, 'vi', 'An Khê', 'Thị Xã'),
(449, 'vi', 'Ayun Pa', 'Thị Xã'),
(450, 'vi', 'Kbang', 'Huyện'),
(451, 'vi', 'Đăk Đoa', 'Huyện'),
(452, 'vi', 'Chư Păh', 'Huyện'),
(453, 'vi', 'Ia Grai', 'Huyện'),
(454, 'vi', 'Mang Yang', 'Huyện'),
(455, 'vi', 'Kông Chro', 'Huyện'),
(456, 'vi', 'Đức Cơ', 'Huyện'),
(457, 'vi', 'Chư Prông', 'Huyện'),
(458, 'vi', 'Chư Sê', 'Huyện'),
(459, 'vi', 'Đăk Pơ', 'Huyện'),
(460, 'vi', 'Ia Pa', 'Huyện'),
(461, 'vi', 'Krông Pa', 'Huyện'),
(462, 'vi', 'Phú Thiện', 'Huyện'),
(463, 'vi', 'Chư Pưh', 'Huyện'),
(464, 'vi', 'Buôn Ma Thuột', 'Thành Phố'),
(465, 'vi', 'Buôn Hồ', 'Thị Xã'),
(466, 'vi', 'Ea H\'leo', 'Huyện'),
(467, 'vi', 'Ea Súp', 'Huyện'),
(468, 'vi', 'Buôn Đôn', 'Huyện'),
(469, 'vi', 'Cư M\'gar', 'Huyện'),
(470, 'vi', 'Krông Búk', 'Huyện'),
(471, 'vi', 'Krông Năng', 'Huyện'),
(472, 'vi', 'Ea Kar', 'Huyện'),
(473, 'vi', 'M\'đrắk', 'Huyện'),
(474, 'vi', 'Krông Bông', 'Huyện'),
(475, 'vi', 'Krông Pắc', 'Huyện'),
(476, 'vi', 'Krông A Na', 'Huyện'),
(477, 'vi', 'Lắk', 'Huyện'),
(478, 'vi', 'Cư Kuin', 'Huyện'),
(479, 'vi', 'Gia Nghĩa', 'Thị Xã'),
(480, 'vi', 'Đắk Glong', 'Huyện'),
(481, 'vi', 'Cư Jút', 'Huyện'),
(482, 'vi', 'Đắk Mil', 'Huyện'),
(483, 'vi', 'Krông Nô', 'Huyện'),
(484, 'vi', 'Đắk Song', 'Huyện'),
(485, 'vi', 'Đắk R\'lấp', 'Huyện'),
(486, 'vi', 'Tuy Đức', 'Huyện'),
(487, 'vi', 'Đà Lạt', 'Thành Phố'),
(488, 'vi', 'Bảo Lộc', 'Thị Xã'),
(489, 'vi', 'Đam Rông', 'Huyện'),
(490, 'vi', 'Lạc Dương', 'Huyện'),
(491, 'vi', 'Lâm Hà', 'Huyện'),
(492, 'vi', 'Đơn Dương', 'Huyện'),
(493, 'vi', 'Đức Trọng', 'Huyện'),
(494, 'vi', 'Di Linh', 'Huyện'),
(495, 'vi', 'Bảo Lâm', 'Huyện'),
(496, 'vi', 'Đạ Huoai', 'Huyện'),
(497, 'vi', 'Đạ Tẻh', 'Huyện'),
(498, 'vi', 'Cát Tiên', 'Huyện'),
(499, 'vi', 'Phước Long', 'Thị Xã'),
(500, 'vi', 'Đồng Xoài', 'Thị Xã'),
(501, 'vi', 'Bình Long', 'Thị Xã'),
(502, 'vi', 'Bù Gia Mập', 'Huyện'),
(503, 'vi', 'Lộc Ninh', 'Huyện'),
(504, 'vi', 'Bù Đốp', 'Huyện'),
(505, 'vi', 'Hớn Quản', 'Huyện'),
(506, 'vi', 'Đồng Phù', 'Huyện'),
(507, 'vi', 'Bù Đăng', 'Huyện'),
(508, 'vi', 'Chơn Thành', 'Huyện'),
(509, 'vi', 'Tây Ninh', 'Thị Xã'),
(510, 'vi', 'Tân Biên', 'Huyện'),
(511, 'vi', 'Tân Châu', 'Huyện'),
(512, 'vi', 'Dương Minh Châu', 'Huyện'),
(513, 'vi', 'Châu Thành', 'Huyện'),
(514, 'vi', 'Hòa Thành', 'Huyện'),
(515, 'vi', 'Gò Dầu', 'Huyện'),
(516, 'vi', 'Bến Cầu', 'Huyện'),
(517, 'vi', 'Trảng Bàng', 'Huyện'),
(518, 'vi', 'Thủ Dầu Một', 'Thị Xã'),
(519, 'vi', 'Dầu Tiếng', 'Huyện'),
(520, 'vi', 'Bến Cát', 'Huyện'),
(521, 'vi', 'Phú Giáo', 'Huyện'),
(522, 'vi', 'Tân Uyên', 'Huyện'),
(523, 'vi', 'Dĩ An', 'Huyện'),
(524, 'vi', 'Thuận An', 'Huyện'),
(525, 'vi', 'Biên Hòa', 'Thành Phố'),
(526, 'vi', 'Long Khánh', 'Thị Xã'),
(527, 'vi', 'Tân Phú', 'Huyện'),
(528, 'vi', 'Vĩnh Cửu', 'Huyện'),
(529, 'vi', 'Định Quán', 'Huyện'),
(530, 'vi', 'Trảng Bom', 'Huyện'),
(531, 'vi', 'Thống Nhất', 'Huyện'),
(532, 'vi', 'Cẩm Mỹ', 'Huyện'),
(533, 'vi', 'Long Thành', 'Huyện'),
(534, 'vi', 'Xuân Lộc', 'Huyện'),
(535, 'vi', 'Nhơn Trạch', 'Huyện'),
(536, 'vi', 'Vũng Tầu', 'Thành Phố'),
(537, 'vi', 'Bà Rịa', 'Thị Xã'),
(538, 'vi', 'Châu Đức', 'Huyện'),
(539, 'vi', 'Xuyên Mộc', 'Huyện'),
(540, 'vi', 'Long Điền', 'Huyện'),
(541, 'vi', 'Đất Đỏ', 'Huyện'),
(542, 'vi', 'Tân Thành', 'Huyện'),
(543, 'vi', 'Côn Đảo', 'Huyện'),
(544, 'vi', '1', 'Quận'),
(545, 'vi', '12', 'Quận'),
(546, 'vi', 'Thủ Đức', 'Quận'),
(547, 'vi', '9', 'Quận'),
(548, 'vi', 'Gò Vấp', 'Quận'),
(549, 'vi', 'Bình Thạnh', 'Quận'),
(550, 'vi', 'Tân Bình', 'Quận'),
(551, 'vi', 'Tân Phú', 'Quận'),
(552, 'vi', 'Phú Nhuận', 'Quận'),
(553, 'vi', '2', 'Quận'),
(554, 'vi', '3', 'Quận'),
(555, 'vi', '10', 'Quận'),
(556, 'vi', '11', 'Quận'),
(557, 'vi', '4', 'Quận'),
(558, 'vi', '5', 'Quận'),
(559, 'vi', '6', 'Quận'),
(560, 'vi', '8', 'Quận'),
(561, 'vi', 'Bình Tân', 'Quận'),
(562, 'vi', '7', 'Quận'),
(563, 'vi', 'Củ Chi', 'Huyện'),
(564, 'vi', 'Hóc Môn', 'Huyện'),
(565, 'vi', 'Bình Chánh', 'Huyện'),
(566, 'vi', 'Nhà Bè', 'Huyện'),
(567, 'vi', 'Cần Giờ', 'Huyện'),
(568, 'vi', 'Tân An', 'Thành Phố'),
(569, 'vi', 'Tân Hưng', 'Huyện'),
(570, 'vi', 'Vĩnh Hưng', 'Huyện'),
(571, 'vi', 'Mộc Hóa', 'Huyện'),
(572, 'vi', 'Tân Thạnh', 'Huyện'),
(573, 'vi', 'Thạnh Hóa', 'Huyện'),
(574, 'vi', 'Đức Huệ', 'Huyện'),
(575, 'vi', 'Đức Hòa', 'Huyện'),
(576, 'vi', 'Bến Lức', 'Huyện'),
(577, 'vi', 'Thủ Thừa', 'Huyện'),
(578, 'vi', 'Tân Trụ', 'Huyện'),
(579, 'vi', 'Cần Đước', 'Huyện'),
(580, 'vi', 'Cần Giuộc', 'Huyện'),
(581, 'vi', 'Châu Thành', 'Huyện'),
(582, 'vi', 'Mỹ Tho', 'Thành Phố'),
(583, 'vi', 'Gò Công', 'Thị Xã'),
(584, 'vi', 'Tân Phước', 'Huyện'),
(585, 'vi', 'Cái Bè', 'Huyện'),
(586, 'vi', 'Cai Lậy', 'Huyện'),
(587, 'vi', 'Châu Thành', 'Huyện'),
(588, 'vi', 'Chợ Gạo', 'Huyện'),
(589, 'vi', 'Gò Công Tây', 'Huyện'),
(590, 'vi', 'Gò Công Đông', 'Huyện'),
(591, 'vi', 'Tân Phú Đông', 'Huyện'),
(592, 'vi', 'Bến Tre', 'Thành Phố'),
(593, 'vi', 'Châu Thành', 'Huyện'),
(594, 'vi', 'Chợ Lách', 'Huyện'),
(595, 'vi', 'Mỏ Cày Nam', 'Huyện'),
(596, 'vi', 'Giồng Trôm', 'Huyện'),
(597, 'vi', 'Bình Đại', 'Huyện'),
(598, 'vi', 'Ba Tri', 'Huyện'),
(599, 'vi', 'Thạnh Phú', 'Huyện'),
(600, 'vi', 'Mỏ Cày Bắc', 'Huyện'),
(601, 'vi', 'Trà Vinh', 'Thị Xã'),
(602, 'vi', 'Càng Long', 'Huyện'),
(603, 'vi', 'Cầu Kè', 'Huyện'),
(604, 'vi', 'Tiểu Cần', 'Huyện'),
(605, 'vi', 'Châu Thành', 'Huyện'),
(606, 'vi', 'Cầu Ngang', 'Huyện'),
(607, 'vi', 'Trà Cú', 'Huyện'),
(608, 'vi', 'Duyên Hải', 'Huyện'),
(609, 'vi', 'Vĩnh Long', 'Thành Phố'),
(610, 'vi', 'Long Hồ', 'Huyện'),
(611, 'vi', 'Mang Thít', 'Huyện'),
(612, 'vi', 'Vũng Liêm', 'Huyện'),
(613, 'vi', 'Tam Bình', 'Huyện'),
(614, 'vi', 'Bình Minh', 'Huyện'),
(615, 'vi', 'Trà Ôn', 'Huyện'),
(616, 'vi', 'Bình Tân', 'Huyện'),
(617, 'vi', 'Cao Lãnh', 'Thành Phố'),
(618, 'vi', 'Sa Đéc', 'Thị Xã'),
(619, 'vi', 'Hồng Ngự', 'Thị Xã'),
(620, 'vi', 'Tân Hồng', 'Huyện'),
(621, 'vi', 'Hồng Ngự', 'Huyện'),
(622, 'vi', 'Tam Nông', 'Huyện'),
(623, 'vi', 'Tháp Mười', 'Huyện'),
(624, 'vi', 'Cao Lãnh', 'Huyện'),
(625, 'vi', 'Thanh Bình', 'Huyện'),
(626, 'vi', 'Lấp Vò', 'Huyện'),
(627, 'vi', 'Lai Vung', 'Huyện'),
(628, 'vi', 'Châu Thành', 'Huyện'),
(629, 'vi', 'Long Xuyên', 'Thành Phố'),
(630, 'vi', 'Châu Đốc', 'Thị Xã'),
(631, 'vi', 'An Phú', 'Huyện'),
(632, 'vi', 'Tân Châu', 'Thị Xã'),
(633, 'vi', 'Phú Tân', 'Huyện'),
(634, 'vi', 'Châu Phú', 'Huyện'),
(635, 'vi', 'Tịnh Biên', 'Huyện'),
(636, 'vi', 'Tri Tôn', 'Huyện'),
(637, 'vi', 'Châu Thành', 'Huyện'),
(638, 'vi', 'Chợ Mới', 'Huyện'),
(639, 'vi', 'Thoại Sơn', 'Huyện'),
(640, 'vi', 'Rạch Giá', 'Thành Phố'),
(641, 'vi', 'Hà Tiên', 'Thị Xã'),
(642, 'vi', 'Kiên Lương', 'Huyện'),
(643, 'vi', 'Hòn Đất', 'Huyện'),
(644, 'vi', 'Tân Hiệp', 'Huyện'),
(645, 'vi', 'Châu Thành', 'Huyện'),
(646, 'vi', 'Giồng Giềng', 'Huyện'),
(647, 'vi', 'Gò Quao', 'Huyện'),
(648, 'vi', 'An Biên', 'Huyện'),
(649, 'vi', 'An Minh', 'Huyện'),
(650, 'vi', 'Vĩnh Thuận', 'Huyện'),
(651, 'vi', 'Phú Quốc', 'Huyện'),
(652, 'vi', 'Kiên Hải', 'Huyện'),
(653, 'vi', 'U Minh Thượng', 'Huyện'),
(654, 'vi', 'Giang Thành', 'Huyện'),
(655, 'vi', 'Ninh Kiều', 'Quận'),
(656, 'vi', 'Ô Môn', 'Quận'),
(657, 'vi', 'Bình Thuỷ', 'Quận'),
(658, 'vi', 'Cái Răng', 'Quận'),
(659, 'vi', 'Thốt Nốt', 'Quận'),
(660, 'vi', 'Vĩnh Thạnh', 'Huyện'),
(661, 'vi', 'Cờ Đỏ', 'Huyện'),
(662, 'vi', 'Phong Điền', 'Huyện'),
(663, 'vi', 'Thới Lai', 'Huyện'),
(664, 'vi', 'Vị Thanh', 'Thị Xã'),
(665, 'vi', 'Ngã Bảy', 'Thị Xã'),
(666, 'vi', 'Châu Thành A', 'Huyện'),
(667, 'vi', 'Châu Thành', 'Huyện'),
(668, 'vi', 'Phụng Hiệp', 'Huyện'),
(669, 'vi', 'Vị Thuỷ', 'Huyện'),
(670, 'vi', 'Long Mỹ', 'Huyện'),
(671, 'vi', 'Sóc Trăng', 'Thành Phố'),
(672, 'vi', 'Châu Thành', 'Huyện'),
(673, 'vi', 'Kế Sách', 'Huyện'),
(674, 'vi', 'Mỹ Tú', 'Huyện'),
(675, 'vi', 'Cù Lao Dung', 'Huyện'),
(676, 'vi', 'Long Phú', 'Huyện'),
(677, 'vi', 'Mỹ Xuyên', 'Huyện'),
(678, 'vi', 'Ngã Năm', 'Huyện'),
(679, 'vi', 'Thạnh Trị', 'Huyện'),
(680, 'vi', 'Vĩnh Châu', 'Huyện'),
(681, 'vi', 'Trần Đề', 'Huyện'),
(682, 'vi', 'Bạc Liêu', 'Thị Xã'),
(683, 'vi', 'Hồng Dân', 'Huyện'),
(684, 'vi', 'Phước Long', 'Huyện'),
(685, 'vi', 'Vĩnh Lợi', 'Huyện'),
(686, 'vi', 'Giá Rai', 'Huyện'),
(687, 'vi', 'Đông Hải', 'Huyện'),
(688, 'vi', 'Hoà Bình', 'Huyện'),
(689, 'vi', 'Cà Mau', 'Thành Phố'),
(690, 'vi', 'U Minh', 'Huyện'),
(691, 'vi', 'Thới Bình', 'Huyện'),
(692, 'vi', 'Trần Văn Thời', 'Huyện'),
(693, 'vi', 'Cái Nước', 'Huyện'),
(694, 'vi', 'Đầm Dơi', 'Huyện'),
(695, 'vi', 'Năm Căn', 'Huyện'),
(696, 'vi', 'Phú Tân', 'Huyện'),
(697, 'vi', 'Ngọc Hiển', 'Huyện');
COMMIT;
