<?php
/**
 *  * Created by PhpStorm.
 * Date: 6/28/2018
 * Time: 2:01 AM
 */

define('SUCCESS_REQUEST', 200);

/*
 * Required
 */
define('ERROR_CODE_REQUIRED_EMAIL',100);
define('ERROR_CODE_REQUIRED_PASSWORD',101);
define('ERROR_CODE_REQUIRED_NAME',102);
define('ERROR_CODE_REQUIRED_BIRTHDAY',103);
define('ERROR_CODE_REQUIRED_ADDRESS',104);
define('ERROR_CODE_REQUIRED_GENDER',105);
define('ERROR_CODE_REQUIRED_RATING',106);
define('ERROR_CODE_REQUIRED_DEVICE_TOKEN',107);
define('ERROR_CODE_REQUIRED_DEVICE_TYPE',108);
define('ERROR_CODE_REQUIRED_LAT_LNG',109);
define('ERROR_CODE_REQUIRED_SOURCE',110);
define('ERROR_CODE_REQUIRED_DESTINATION',111);
define('ERROR_CODE_REQUIRED_PHONE',112);
define('ERROR_CODE_REQUIRED_TOKEN',114);
define('ERROR_CODE_REQUIRED_OTP',115);
define('ERROR_CODE_REQUIRED_PAYMENT_METHOD_ID',116);
define('ERROR_CODE_REQUIRED_RESTAURANT_NAME',117);
define('ERROR_CODE_REQUIRED_RESTAURANT_ADDRESS',118);
define('ERROR_CODE_REQUIRED_RESTAURANT_OPEN_TIME',119);
define('ERROR_CODE_REQUIRED_RESTAURANT_DESCRIPTION',120);
define('ERROR_CODE_REQUIRED_RESTAURANT_PRIMARY_PHOTO',121);
define('ERROR_CODE_REQUIRED_CATEGORY_ID',122);
define('ERROR_CODE_REQUIRED_CUSTOM_AUTH_FIREBASE',123);
define('ERROR_CODE_REQUIRED_PROVINCE',124);



/*
 * Invalid
 */
define('ERROR_CODE_INVALID_ACCOUNT',600);
define('ERROR_CODE_INVALID_TOKEN',601);
define('ERROR_CODE_INVALID_OLD_PASSWORD',602);
define('ERROR_CODE_ACCOUNT_BLOCKED_OR_NOT_ACTIVE',603);
define('ERROR_CODE_ACCOUNT_NOT_EXISTS',604);


/*
 * Server notification
 */
define('ERROR_CODE_UNAUTHORIZED',401);
define('ERROR_CODE_FORBIDDEN',403);
define('ERROR_CODE_SERVER_ERROR',500);
define('ERROR_CODE_BAD_GATEWAY',502);


/*
 * Other error code
 */
define('ERROR_CODE_FILE_LARGE',700);
define('ERROR_CODE_SESSION_EXPIRED',701);
define('ERROR_CODE_NO_EXIST_DATA',702);
define('ERROR_CODE_NOT_ENOUGH_BALANCE',703);
define('ERROR_CODE_ALREADY_EXISTS',704);
define('ERROR_CODE_FILE_INVALID',705);
define('ERROR_CODE_CARD_INVALID',709);
define('ERROR_CODE_NOT_PATH',710);
define('ERROR_CODE_OUT_OF_STOCK',711);
define('ERROR_CODE_REQUIRE_TWO_FA',712);
